//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLM_Lynx._03_GUI_User_Interface._3_2_Relation_Part.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_RelationPart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_RelationPart() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLM_Lynx._03_GUI_User_Interface._3_2_Relation_Part.Lang.Lang_RelationPart", typeof(Lang_RelationPart).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp;Child.
        /// </summary>
        internal static string btnAddChild {
            get {
                return ResourceManager.GetString("btnAddChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add  &amp;Parent.
        /// </summary>
        internal static string btnAddParent {
            get {
                return ResourceManager.GetString("btnAddParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string btnCheck {
            get {
                return ResourceManager.GetString("btnCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnClearChild {
            get {
                return ResourceManager.GetString("btnClearChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete Child.
        /// </summary>
        internal static string btnDelChild {
            get {
                return ResourceManager.GetString("btnDelChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnDeleteParent {
            get {
                return ResourceManager.GetString("btnDeleteParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Parts.
        /// </summary>
        internal static string btnHistory {
            get {
                return ResourceManager.GetString("btnHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make request ( ECO ).
        /// </summary>
        internal static string btnUpload {
            get {
                return ResourceManager.GetString("btnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Relation Part.
        /// </summary>
        internal static string i_form {
            get {
                return ResourceManager.GetString("i.form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter keyword for find.
        /// </summary>
        internal static string lb1 {
            get {
                return ResourceManager.GetString("lb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Code.
        /// </summary>
        internal static string lb2 {
            get {
                return ResourceManager.GetString("lb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Name.
        /// </summary>
        internal static string lb3 {
            get {
                return ResourceManager.GetString("lb3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptions.
        /// </summary>
        internal static string lb4 {
            get {
                return ResourceManager.GetString("lb4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Status.
        /// </summary>
        internal static string lb5 {
            get {
                return ResourceManager.GetString("lb5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to open file in list Files.
        /// </summary>
        internal static string lb6 {
            get {
                return ResourceManager.GetString("lb6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string t0 {
            get {
                return ResourceManager.GetString("t0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter the Search textbox.
        /// </summary>
        internal static string t1 {
            get {
                return ResourceManager.GetString("t1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : This Part Code is the same the Part Parent Code..
        /// </summary>
        internal static string t10 {
            get {
                return ResourceManager.GetString("t10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Part is added in List Child.
        /// </summary>
        internal static string t11 {
            get {
                return ResourceManager.GetString("t11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Part : || .
        /// </summary>
        internal static string t12 {
            get {
                return ResourceManager.GetString("t12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the Child List.
        /// </summary>
        internal static string t13 {
            get {
                return ResourceManager.GetString("t13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this row ?.
        /// </summary>
        internal static string t14 {
            get {
                return ResourceManager.GetString("t14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not have row to delete.
        /// </summary>
        internal static string t15 {
            get {
                return ResourceManager.GetString("t15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clear the List Child ?.
        /// </summary>
        internal static string t16 {
            get {
                return ResourceManager.GetString("t16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to check information before make the request..
        /// </summary>
        internal static string t17 {
            get {
                return ResourceManager.GetString("t17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string t18 {
            get {
                return ResourceManager.GetString("t18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string t19 {
            get {
                return ResourceManager.GetString("t19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit &quot;create relation tab &quot; ? .
        /// </summary>
        internal static string t2 {
            get {
                return ResourceManager.GetString("t2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string t20 {
            get {
                return ResourceManager.GetString("t20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string t21 {
            get {
                return ResourceManager.GetString("t21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string t22 {
            get {
                return ResourceManager.GetString("t22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string t23 {
            get {
                return ResourceManager.GetString("t23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find the match data.
        /// </summary>
        internal static string t3 {
            get {
                return ResourceManager.GetString("t3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have not data to add parent.
        /// </summary>
        internal static string t4 {
            get {
                return ResourceManager.GetString("t4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This part is in the List Child. Please choose other parts.
        /// </summary>
        internal static string t5 {
            get {
                return ResourceManager.GetString("t5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have files in data server..
        /// </summary>
        internal static string t6 {
            get {
                return ResourceManager.GetString("t6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find any files in data server..
        /// </summary>
        internal static string t7 {
            get {
                return ResourceManager.GetString("t7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find image.
        /// </summary>
        internal static string t8 {
            get {
                return ResourceManager.GetString("t8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have not data.
        /// </summary>
        internal static string t9 {
            get {
                return ResourceManager.GetString("t9", resourceCulture);
            }
        }
    }
}
