//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLM_Lynx._03_GUI_User_Interface._3_1_Login {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_Login() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLM_Lynx._03_GUI_User_Interface._3_1_Login.Language_Login", typeof(Language_Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string btn_Add {
            get {
                return ResourceManager.GetString("btn.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Dept.
        /// </summary>
        internal static string btn_AddDept {
            get {
                return ResourceManager.GetString("btn.AddDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btn_Del {
            get {
                return ResourceManager.GetString("btn.Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string btn_Modify {
            get {
                return ResourceManager.GetString("btn.Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btn_Save {
            get {
                return ResourceManager.GetString("btn.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage List Department.
        /// </summary>
        internal static string gr_ManageDept {
            get {
                return ResourceManager.GetString("gr.ManageDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage List User.
        /// </summary>
        internal static string gr_ManageListUser {
            get {
                return ResourceManager.GetString("gr.ManageListUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string lb_Dept {
            get {
                return ResourceManager.GetString("lb.Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeptName.
        /// </summary>
        internal static string lb_DeptName {
            get {
                return ResourceManager.GetString("lb.DeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManagerUser.
        /// </summary>
        internal static string lb_form {
            get {
                return ResourceManager.GetString("lb.form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string lb_Level {
            get {
                return ResourceManager.GetString("lb.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lb_Name {
            get {
                return ResourceManager.GetString("lb.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lb_Pass {
            get {
                return ResourceManager.GetString("lb.Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string lb_Pos {
            get {
                return ResourceManager.GetString("lb.Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string lb_Rol {
            get {
                return ResourceManager.GetString("lb.Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of users has reached the limit, no more new users can be added..
        /// </summary>
        internal static string t1 {
            get {
                return ResourceManager.GetString("t1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not have data. Please check datatabase again..
        /// </summary>
        internal static string t10 {
            get {
                return ResourceManager.GetString("t10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Current mode:  &quot;Add&quot; .
        /// </summary>
        internal static string t11 {
            get {
                return ResourceManager.GetString("t11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to add ID.
        /// </summary>
        internal static string t12 {
            get {
                return ResourceManager.GetString("t12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to add Department.
        /// </summary>
        internal static string t13 {
            get {
                return ResourceManager.GetString("t13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New department : .
        /// </summary>
        internal static string t14 {
            get {
                return ResourceManager.GetString("t14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Department had been added successfully.
        /// </summary>
        internal static string t15 {
            get {
                return ResourceManager.GetString("t15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !!!  Check the input data again.
        /// </summary>
        internal static string t16 {
            get {
                return ResourceManager.GetString("t16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to modify user name ?.
        /// </summary>
        internal static string t17 {
            get {
                return ResourceManager.GetString("t17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify user successfully.
        /// </summary>
        internal static string t18 {
            get {
                return ResourceManager.GetString("t18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not have data.
        /// </summary>
        internal static string t19 {
            get {
                return ResourceManager.GetString("t19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add new user ?.
        /// </summary>
        internal static string t2 {
            get {
                return ResourceManager.GetString("t2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete ----.
        /// </summary>
        internal static string t20 {
            get {
                return ResourceManager.GetString("t20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user succesfully..
        /// </summary>
        internal static string t21 {
            get {
                return ResourceManager.GetString("t21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !!!. Can not delete user in database..
        /// </summary>
        internal static string t22 {
            get {
                return ResourceManager.GetString("t22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode : Add New Department.
        /// </summary>
        internal static string t23 {
            get {
                return ResourceManager.GetString("t23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify department successfully : .
        /// </summary>
        internal static string t24 {
            get {
                return ResourceManager.GetString("t24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !!!. Can not delete department in database..
        /// </summary>
        internal static string t25 {
            get {
                return ResourceManager.GetString("t25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the new department.
        /// </summary>
        internal static string t26 {
            get {
                return ResourceManager.GetString("t26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete ---.
        /// </summary>
        internal static string t27 {
            get {
                return ResourceManager.GetString("t27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Department succesfully..
        /// </summary>
        internal static string t28 {
            get {
                return ResourceManager.GetString("t28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !!!. Can not delete department in database..
        /// </summary>
        internal static string t29 {
            get {
                return ResourceManager.GetString("t29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name : .
        /// </summary>
        internal static string t3 {
            get {
                return ResourceManager.GetString("t3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role : .
        /// </summary>
        internal static string t4 {
            get {
                return ResourceManager.GetString("t4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position : .
        /// </summary>
        internal static string t5 {
            get {
                return ResourceManager.GetString("t5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department :.
        /// </summary>
        internal static string t6 {
            get {
                return ResourceManager.GetString("t6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice : .
        /// </summary>
        internal static string t7 {
            get {
                return ResourceManager.GetString("t7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User had been added successfully.
        /// </summary>
        internal static string t8 {
            get {
                return ResourceManager.GetString("t8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the input data again..
        /// </summary>
        internal static string t9 {
            get {
                return ResourceManager.GetString("t9", resourceCulture);
            }
        }
    }
}
