//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLM_Lynx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLM_Lynx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Part Recently.
        /// </summary>
        internal static string _0_1 {
            get {
                return ResourceManager.GetString("0.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose quantity for view.
        /// </summary>
        internal static string _0_2 {
            get {
                return ResourceManager.GetString("0.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortkey to close : Escape.
        /// </summary>
        internal static string _0_3 {
            get {
                return ResourceManager.GetString("0.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string _0_4 {
            get {
                return ResourceManager.GetString("0.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show 5 most recent parts.
        /// </summary>
        internal static string _0_5 {
            get {
                return ResourceManager.GetString("0.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show 10 most recent parts.
        /// </summary>
        internal static string _0_6 {
            get {
                return ResourceManager.GetString("0.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show 20 most recent parts.
        /// </summary>
        internal static string _0_7 {
            get {
                return ResourceManager.GetString("0.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show 50 most recent parts.
        /// </summary>
        internal static string _0_8 {
            get {
                return ResourceManager.GetString("0.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : .
        /// </summary>
        internal static string _0_9 {
            get {
                return ResourceManager.GetString("0.9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the active code.
        /// </summary>
        internal static string _1_1_1 {
            get {
                return ResourceManager.GetString("1.1.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !!! Please enter active code again.
        /// </summary>
        internal static string _1_1_2 {
            get {
                return ResourceManager.GetString("1.1.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active  successfully ! Please reset application.
        /// </summary>
        internal static string _1_1_3 {
            get {
                return ResourceManager.GetString("1.1.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !!!, Please check again.
        /// </summary>
        internal static string _1_1_4 {
            get {
                return ResourceManager.GetString("1.1.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !!!, Please enter active code again.
        /// </summary>
        internal static string _1_1_5 {
            get {
                return ResourceManager.GetString("1.1.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date : .
        /// </summary>
        internal static string _1_2_1 {
            get {
                return ResourceManager.GetString("1.2.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string _1_2_10 {
            get {
                return ResourceManager.GetString("1.2.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string _1_2_11 {
            get {
                return ResourceManager.GetString("1.2.11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or Password are wrong.
        /// </summary>
        internal static string _1_2_12 {
            get {
                return ResourceManager.GetString("1.2.12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successfully.
        /// </summary>
        internal static string _1_2_2 {
            get {
                return ResourceManager.GetString("1.2.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit application ?.
        /// </summary>
        internal static string _1_2_3 {
            get {
                return ResourceManager.GetString("1.2.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string _1_2_4 {
            get {
                return ResourceManager.GetString("1.2.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find company image.
        /// </summary>
        internal static string _1_2_5 {
            get {
                return ResourceManager.GetString("1.2.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string _1_2_6 {
            get {
                return ResourceManager.GetString("1.2.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string _1_2_7 {
            get {
                return ResourceManager.GetString("1.2.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string _1_2_8 {
            get {
                return ResourceManager.GetString("1.2.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string _1_2_9 {
            get {
                return ResourceManager.GetString("1.2.9", resourceCulture);
            }
        }
    }
}
