//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLM_Lynx.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=61.14.233.166;Initial Catalog=SAMPLE_0;User ID=sa;;Password=\"yourStro" +
            "ngPass@123003\";Trust Server Certificate=True; Connect Timeout=60;")]
        public string Datacon {
            get {
                return ((string)(this["Datacon"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"C:\\Program Files\\Autodesk\\DWG TrueView 2023 - English\\dwgviewr.exe\"")]
        public string DWGTrueViewPath {
            get {
                return ((string)(this["DWGTrueViewPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"C:\\Program Files\\Common Files\\eDrawings2025\\eDrawings.exe\"")]
        public string eDrawingView {
            get {
                return ((string)(this["eDrawingView"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Admin\\source\\repos\\LinhToBK\\PLM\\04_Image\\ABCCoLtd.jpg")]
        public string ABCCoLtd {
            get {
                return ((string)(this["ABCCoLtd"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Admin\\OneDrive\\WORKING DSGLOBAL\\06. PLM Lynx\\SAMPLE_0\\DATA\\")]
        public string LinkDataPart {
            get {
                return ((string)(this["LinkDataPart"]));
            }
            set {
                this["LinkDataPart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Admin\\OneDrive\\WORKING DSGLOBAL\\06. PLM Lynx\\SAMPLE_0\\TRASH\\")]
        public string TrashDataPart {
            get {
                return ((string)(this["TrashDataPart"]));
            }
            set {
                this["TrashDataPart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Admin\\OneDrive\\WORKING DSGLOBAL\\06. PLM Lynx\\SAMPLE_0\\PODATA\\")]
        public string POData {
            get {
                return ((string)(this["POData"]));
            }
            set {
                this["POData"] = value;
            }
        }
    }
}
