//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLM_Lynx._03_GUI_User_Interface._3_5_Purchase.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_frmMakePO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_frmMakePO() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLM_Lynx._03_GUI_User_Interface._3_5_Purchase.Lang.Lang_frmMakePO", typeof(Lang_frmMakePO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make New PO.
        /// </summary>
        internal static string i_form {
            get {
                return ResourceManager.GetString("i.form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lb1 {
            get {
                return ResourceManager.GetString("lb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO No.
        /// </summary>
        internal static string lb10 {
            get {
                return ResourceManager.GetString("lb10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        internal static string lb11 {
            get {
                return ResourceManager.GetString("lb11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        internal static string lb12 {
            get {
                return ResourceManager.GetString("lb12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        internal static string lb13 {
            get {
                return ResourceManager.GetString("lb13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier ID.
        /// </summary>
        internal static string lb14 {
            get {
                return ResourceManager.GetString("lb14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Location.
        /// </summary>
        internal static string lb15 {
            get {
                return ResourceManager.GetString("lb15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Tel.
        /// </summary>
        internal static string lb16 {
            get {
                return ResourceManager.GetString("lb16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxID.
        /// </summary>
        internal static string lb17 {
            get {
                return ResourceManager.GetString("lb17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string lb18 {
            get {
                return ResourceManager.GetString("lb18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments \n Terms.
        /// </summary>
        internal static string lb19 {
            get {
                return ResourceManager.GetString("lb19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string lb2 {
            get {
                return ResourceManager.GetString("lb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item for PO.
        /// </summary>
        internal static string lb20 {
            get {
                return ResourceManager.GetString("lb20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item.
        /// </summary>
        internal static string lb21 {
            get {
                return ResourceManager.GetString("lb21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear List.
        /// </summary>
        internal static string lb22 {
            get {
                return ResourceManager.GetString("lb22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Excel.
        /// </summary>
        internal static string lb23 {
            get {
                return ResourceManager.GetString("lb23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save PO.
        /// </summary>
        internal static string lb24 {
            get {
                return ResourceManager.GetString("lb24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string lb25 {
            get {
                return ResourceManager.GetString("lb25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string lb26 {
            get {
                return ResourceManager.GetString("lb26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string lb27 {
            get {
                return ResourceManager.GetString("lb27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept.
        /// </summary>
        internal static string lb3 {
            get {
                return ResourceManager.GetString("lb3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string lb4 {
            get {
                return ResourceManager.GetString("lb4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Near.
        /// </summary>
        internal static string lb5 {
            get {
                return ResourceManager.GetString("lb5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Old.
        /// </summary>
        internal static string lb6 {
            get {
                return ResourceManager.GetString("lb6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find items.
        /// </summary>
        internal static string lb7 {
            get {
                return ResourceManager.GetString("lb7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel PO.
        /// </summary>
        internal static string lb8 {
            get {
                return ResourceManager.GetString("lb8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage company.
        /// </summary>
        internal static string lb9 {
            get {
                return ResourceManager.GetString("lb9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string t0 {
            get {
                return ResourceManager.GetString("t0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the key search.
        /// </summary>
        internal static string t1 {
            get {
                return ResourceManager.GetString("t1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO is currently empty! \nPlease fill in details to purchase.
        /// </summary>
        internal static string t10 {
            get {
                return ResourceManager.GetString("t10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to export to Excel file for preview?.
        /// </summary>
        internal static string t11 {
            get {
                return ResourceManager.GetString("t11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found any items.
        /// </summary>
        internal static string t2 {
            get {
                return ResourceManager.GetString("t2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is already in the list.
        /// </summary>
        internal static string t3 {
            get {
                return ResourceManager.GetString("t3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete item :.
        /// </summary>
        internal static string t4 {
            get {
                return ResourceManager.GetString("t4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List is empty. Please select at least 1 item.
        /// </summary>
        internal static string t5 {
            get {
                return ResourceManager.GetString("t5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to CLEAR ALL ITEM ? .
        /// </summary>
        internal static string t6 {
            get {
                return ResourceManager.GetString("t6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel about - [ Make the New Purchase Order ] ?.
        /// </summary>
        internal static string t7 {
            get {
                return ResourceManager.GetString("t7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PO has been saved to the database successfully..
        /// </summary>
        internal static string t8 {
            get {
                return ResourceManager.GetString("t8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !!!. Please check input information again.
        /// </summary>
        internal static string t9 {
            get {
                return ResourceManager.GetString("t9", resourceCulture);
            }
        }
    }
}
