//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLM_Lynx._03_GUI_User_Interface._3_4_FindPart.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_FindPart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_FindPart() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLM_Lynx._03_GUI_User_Interface._3_4_FindPart.Lang.Lang_FindPart", typeof(Lang_FindPart).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Part.
        /// </summary>
        internal static string i_form {
            get {
                return ResourceManager.GetString("i.form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search information of Part.
        /// </summary>
        internal static string lb1 {
            get {
                return ResourceManager.GetString("lb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Image.
        /// </summary>
        internal static string lb10 {
            get {
                return ResourceManager.GetString("lb10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search All Data.
        /// </summary>
        internal static string lb2 {
            get {
                return ResourceManager.GetString("lb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List new parts recently.
        /// </summary>
        internal static string lb3 {
            get {
                return ResourceManager.GetString("lb3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        internal static string lb4 {
            get {
                return ResourceManager.GetString("lb4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information of the clicked part.
        /// </summary>
        internal static string lb5 {
            get {
                return ResourceManager.GetString("lb5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Parent Part.
        /// </summary>
        internal static string lb6 {
            get {
                return ResourceManager.GetString("lb6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Child Part.
        /// </summary>
        internal static string lb7 {
            get {
                return ResourceManager.GetString("lb7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download BOM.
        /// </summary>
        internal static string lb8 {
            get {
                return ResourceManager.GetString("lb8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Drawing.
        /// </summary>
        internal static string lb9 {
            get {
                return ResourceManager.GetString("lb9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string t0 {
            get {
                return ResourceManager.GetString("t0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the number is wrong.
        /// </summary>
        internal static string t1 {
            get {
                return ResourceManager.GetString("t1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string t10 {
            get {
                return ResourceManager.GetString("t10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string t11 {
            get {
                return ResourceManager.GetString("t11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need enter the key in textbox.
        /// </summary>
        internal static string t2 {
            get {
                return ResourceManager.GetString("t2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is empty.
        /// </summary>
        internal static string t3 {
            get {
                return ResourceManager.GetString("t3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to export BOM List ?.
        /// </summary>
        internal static string t4 {
            get {
                return ResourceManager.GetString("t4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string t5 {
            get {
                return ResourceManager.GetString("t5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string t6 {
            get {
                return ResourceManager.GetString("t6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string t7 {
            get {
                return ResourceManager.GetString("t7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string t8 {
            get {
                return ResourceManager.GetString("t8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string t9 {
            get {
                return ResourceManager.GetString("t9", resourceCulture);
            }
        }
    }
}
