//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLM_Lynx._03_GUI_User_Interface._3_3_ECO.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_frmECO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_frmECO() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLM_Lynx._03_GUI_User_Interface._3_3_ECO.Lang.Lang_frmECO", typeof(Lang_frmECO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering Change Order ( ECO ).
        /// </summary>
        internal static string i_form {
            get {
                return ResourceManager.GetString("i.form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note : 
        ///1. Update information of Part
        ///2. Update relation of Parts
        ///3. Delete relation of Parts.
        /// </summary>
        internal static string lb1 {
            get {
                return ResourceManager.GetString("lb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Part.
        /// </summary>
        internal static string lb10 {
            get {
                return ResourceManager.GetString("lb10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent infor.
        /// </summary>
        internal static string lb11 {
            get {
                return ResourceManager.GetString("lb11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child infor.
        /// </summary>
        internal static string lb12 {
            get {
                return ResourceManager.GetString("lb12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show List Child.
        /// </summary>
        internal static string lb13 {
            get {
                return ResourceManager.GetString("lb13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify quantity.
        /// </summary>
        internal static string lb14 {
            get {
                return ResourceManager.GetString("lb14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete relation.
        /// </summary>
        internal static string lb15 {
            get {
                return ResourceManager.GetString("lb15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string lb16 {
            get {
                return ResourceManager.GetString("lb16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECO Relation: 
        ///1. If you  delete relation, you must create new relation.
        ///2. Change quantity of child in parent part.
        /// </summary>
        internal static string lb17 {
            get {
                return ResourceManager.GetString("lb17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp;Parent.
        /// </summary>
        internal static string lb18 {
            get {
                return ResourceManager.GetString("lb18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp;Child.
        /// </summary>
        internal static string lb19 {
            get {
                return ResourceManager.GetString("lb19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short key :
        ///+) Alt + T =&gt; Add Part to update information 
        ///+) Alt + P =&gt; Add Parent to update relation
        ///+) Alt + C =&gt; Add Child to update relation
        ///+) Alt + L =&gt; Check List Child
        ///.
        /// </summary>
        internal static string lb2 {
            get {
                return ResourceManager.GetString("lb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keysearch.
        /// </summary>
        internal static string lb3 {
            get {
                return ResourceManager.GetString("lb3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lb4 {
            get {
                return ResourceManager.GetString("lb4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Part.
        /// </summary>
        internal static string lb5 {
            get {
                return ResourceManager.GetString("lb5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create relation request.
        /// </summary>
        internal static string lb6 {
            get {
                return ResourceManager.GetString("lb6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Part.
        /// </summary>
        internal static string lb7 {
            get {
                return ResourceManager.GetString("lb7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information  of Part.
        /// </summary>
        internal static string lb8 {
            get {
                return ResourceManager.GetString("lb8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Version, Material, Drawing, ...).
        /// </summary>
        internal static string lb9 {
            get {
                return ResourceManager.GetString("lb9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string t0 {
            get {
                return ResourceManager.GetString("t0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not load data of quantity.
        /// </summary>
        internal static string t1 {
            get {
                return ResourceManager.GetString("t1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the [Delete Relation] request successfully..
        /// </summary>
        internal static string t10 {
            get {
                return ResourceManager.GetString("t10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error . Please check data and connection again.
        /// </summary>
        internal static string t11 {
            get {
                return ResourceManager.GetString("t11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to choose the part to update information.
        /// </summary>
        internal static string t12 {
            get {
                return ResourceManager.GetString("t12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string t13 {
            get {
                return ResourceManager.GetString("t13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter the keysearch.
        /// </summary>
        internal static string t2 {
            get {
                return ResourceManager.GetString("t2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit &quot;Make ECO Request&quot; tab ?.
        /// </summary>
        internal static string t3 {
            get {
                return ResourceManager.GetString("t3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not have data in Search List.
        /// </summary>
        internal static string t4 {
            get {
                return ResourceManager.GetString("t4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not have Parent Part Data.
        /// </summary>
        internal static string t5 {
            get {
                return ResourceManager.GetString("t5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of quantity is wrong.
        /// </summary>
        internal static string t6 {
            get {
                return ResourceManager.GetString("t6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to old quantity = new quantity.
        /// </summary>
        internal static string t7 {
            get {
                return ResourceManager.GetString("t7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete relation : .
        /// </summary>
        internal static string t8 {
            get {
                return ResourceManager.GetString("t8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you  delete relation, you must create new relation..
        /// </summary>
        internal static string t9 {
            get {
                return ResourceManager.GetString("t9", resourceCulture);
            }
        }
    }
}
