//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLM_Lynx._03_GUI_User_Interface._3_3_ECO.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_ListECO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_ListECO() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLM_Lynx._03_GUI_User_Interface._3_3_ECO.Lang.Lang_ListECO", typeof(Lang_ListECO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List ECO Update.
        /// </summary>
        internal static string i_form {
            get {
                return ResourceManager.GetString("i.form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECO No.
        /// </summary>
        internal static string lb1 {
            get {
                return ResourceManager.GetString("lb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECO Date.
        /// </summary>
        internal static string lb2 {
            get {
                return ResourceManager.GetString("lb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester.
        /// </summary>
        internal static string lb3 {
            get {
                return ResourceManager.GetString("lb3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECO Status.
        /// </summary>
        internal static string lb4 {
            get {
                return ResourceManager.GetString("lb4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string lb5 {
            get {
                return ResourceManager.GetString("lb5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string t0 {
            get {
                return ResourceManager.GetString("t0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show 5 ECO recently.
        /// </summary>
        internal static string t1 {
            get {
                return ResourceManager.GetString("t1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to data server and delete temp file in ECOTEMP successfully.
        /// </summary>
        internal static string t10 {
            get {
                return ResourceManager.GetString("t10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : Can not delete temp file in ECOTEMP.
        /// </summary>
        internal static string t11 {
            get {
                return ResourceManager.GetString("t11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : Can not copy file to data server.
        /// </summary>
        internal static string t12 {
            get {
                return ResourceManager.GetString("t12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not copy with upgrade version file to data server.
        /// </summary>
        internal static string t13 {
            get {
                return ResourceManager.GetString("t13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not update data to [tblECO] in database.
        /// </summary>
        internal static string t14 {
            get {
                return ResourceManager.GetString("t14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not update data to [tblPart] in database.
        /// </summary>
        internal static string t15 {
            get {
                return ResourceManager.GetString("t15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to approve [ Make new relation of Parts ].
        /// </summary>
        internal static string t16 {
            get {
                return ResourceManager.GetString("t16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved [ Make new relation of Parts ] successfully..
        /// </summary>
        internal static string t17 {
            get {
                return ResourceManager.GetString("t17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to approve [ Update quantity of part ] ?.
        /// </summary>
        internal static string t18 {
            get {
                return ResourceManager.GetString("t18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved [ Update quantity of Part ] successfully..
        /// </summary>
        internal static string t19 {
            get {
                return ResourceManager.GetString("t19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show 10 ECO recently.
        /// </summary>
        internal static string t2 {
            get {
                return ResourceManager.GetString("t2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail : Can not update quantity of part.
        /// </summary>
        internal static string t20 {
            get {
                return ResourceManager.GetString("t20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete relation : .
        /// </summary>
        internal static string t21 {
            get {
                return ResourceManager.GetString("t21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve [ Delete relation ] successfully..
        /// </summary>
        internal static string t22 {
            get {
                return ResourceManager.GetString("t22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail : Can not delete relation.
        /// </summary>
        internal static string t23 {
            get {
                return ResourceManager.GetString("t23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t need to approve when create new part..
        /// </summary>
        internal static string t24 {
            get {
                return ResourceManager.GetString("t24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel : [ Update quantity of part ].
        /// </summary>
        internal static string t25 {
            get {
                return ResourceManager.GetString("t25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel : [ Delete relation parts ].
        /// </summary>
        internal static string t26 {
            get {
                return ResourceManager.GetString("t26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If ECO had approved , you can not cancel.
        /// </summary>
        internal static string t27 {
            get {
                return ResourceManager.GetString("t27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECO had canceled.
        /// </summary>
        internal static string t28 {
            get {
                return ResourceManager.GetString("t28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel : [ Update information of part ].
        /// </summary>
        internal static string t29 {
            get {
                return ResourceManager.GetString("t29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show 20 ECO recently.
        /// </summary>
        internal static string t3 {
            get {
                return ResourceManager.GetString("t3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Canceled Status] successfully.
        /// </summary>
        internal static string t30 {
            get {
                return ResourceManager.GetString("t30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when cancel operation.
        /// </summary>
        internal static string t31 {
            get {
                return ResourceManager.GetString("t31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit View ECO tab ?.
        /// </summary>
        internal static string t32 {
            get {
                return ResourceManager.GetString("t32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel : [ Make new relation of parts].
        /// </summary>
        internal static string t33 {
            get {
                return ResourceManager.GetString("t33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail : Delete in [tblRelationTemp].
        /// </summary>
        internal static string t34 {
            get {
                return ResourceManager.GetString("t34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string t35 {
            get {
                return ResourceManager.GetString("t35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show 50 ECO recently.
        /// </summary>
        internal static string t4 {
            get {
                return ResourceManager.GetString("t4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not have data to choose.
        /// </summary>
        internal static string t5 {
            get {
                return ResourceManager.GetString("t5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new part =&gt; Not need to approve.
        /// </summary>
        internal static string t6 {
            get {
                return ResourceManager.GetString("t6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECO had approved.
        /// </summary>
        internal static string t7 {
            get {
                return ResourceManager.GetString("t7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECO had canceled. You need to make new request..
        /// </summary>
        internal static string t8 {
            get {
                return ResourceManager.GetString("t8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to approve [ Update Information of Part ] : .
        /// </summary>
        internal static string t9 {
            get {
                return ResourceManager.GetString("t9", resourceCulture);
            }
        }
    }
}
